#This is config for ccxt BINANCE  
#MAKE SURE TO SYNC WINDOWS TIME 
BINANCE_API_KEY = 'usK1lkcFnryRUifmiMLPSQZyzpvZmsxqVTeZ0jQ9qczTcLZMCiePHsHXxNRDgldq'
BINANCE_SECRET_KEY = 'iDuNQXnQfVgbBZ0qCzMbcmG51G7GMxAz1NNXNN3dnZ7kw55XO1v1xUsu4Ei8L1YH'
